# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mecanum.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmecanum.proto\"@\n\x0e\x43ontrolRequest\x12\x12\n\nspeed_mmps\x18\x01 \x02(\x05\x12\x0b\n\x03rad\x18\x02 \x02(\x02\x12\r\n\x05omega\x18\x03 \x02(\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mecanum_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTROLREQUEST._serialized_start=17
  _CONTROLREQUEST._serialized_end=81
# @@protoc_insertion_point(module_scope)
